services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 4000:4000
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    ports:
      - 3000:3000
    links:
      - mongo

  mongo:
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
    

networks:
  react-express:
  express-mongo:
